### ISSUE TITLE
Prepare release 0.1.0

### ISSUE THREAD

**Issue by tbouffard** [maxGraph/maxgraph#141]
We have solved the versioning issue, see #92. So we can release a version and publish the package on npm.
See also #41 (May 2021).

**Documentation tasks**
- [x] Review milestone [0.1.0]( https://github.com/maxGraph/maxGraph/milestone/1)
- [x] Configure GitHub auto-generated release notes: https://docs.github.com/en/repositories/releasing-projects-on-github/automatically-generated-release-notes#configuring-automatically-generated-release-notes #142 
- [x] Review repository labels and the labels applied to merged Pull Requests. Labels are used to auto-generate the GH release notes
- [x] Update the Changelog file. List fixes or add a link to the GH release. #146

**Content of the npm package**
- [x] Ensure that a README file is included. To avoid duplication with the main README, it can provide minimal information (description, how to install) and a link to the main README (https://github.com/maxGraph/maxGraph#readme) #144
- [x] Include the LICENSE files #144

**Publishing tasks**
- [x] Publish the npm package: [@maxgraph/core@0.1.0](https://www.npmjs.com/package/@maxgraph/core/v/0.1.0). This will be probably done from a local dev machine. If so list the command that have been run in a comment to let other review. To be improve later by automating with GitHub Actions for instance. Publish steps: https://github.com/maxGraph/maxGraph/issues/141#issuecomment-1323392317
- [x] Update the README #145
  - [x] add a npm status badge
  - [x] update the status paragraph and explain how to install the package

**Comment by tbouffard** [comment]
After merging #142, here is how the auto-generated release notes will look like:

![image](https://user-images.githubusercontent.com/27200110/202922701-b228da42-16de-4c3f-8af9-6aae260c3474.png)

**Comment by tbouffard** [comment]
ℹ️ I should be able to publish the npm package and the release notes today 🤞🏿

**Comment by tbouffard** [comment]
The first version of the npm package has been published: https://www.npmjs.com/package/@maxgraph/core/v/0.1.0

### Manual actions done to tag and publish

**git tag**
commit c60b8496a39538771c4c8eb1bf9962bf5fc5b3c0
git tag v0.1.0
git push origin v0.1.0
 

**npm publish**
from commit c60b8496a39538771c4c8eb1bf9962bf5fc5b3c0 (HEAD -> development, tag: v0.1.0, origin/development)
Run `npm publish --access=public`


### About `--access=public`

This was required for the initial publish and should not be required anymore. See https://docs.npmjs.com/cli/v8/commands/npm-publish#access
> When publishing scoped packages, the access level defaults to restricted. If you want your scoped package to be publicly viewable (and installable) set --access=public. The only valid values for access are public and restricted. Unscoped packages always have an access level of public.
> Note: Using the --access flag on the npm publish command will only set the package access level on the initial publish of the package. Any subsequent npm publish commands using the --access flag will not have an effect to the access level. To make changes to the access level after the initial publish use npm access.
