### ISSUE TITLE
Make the @maxgraph/core package "side effects" free

### ISSUE THREAD

**Issue by tbouffard** [maxGraph/maxgraph#442]
### Is your feature request related to a problem? Please describe.

Currently, in version 0.10.3, the `maxGraph` package is declared as having side effects, and this is for good as it really includes side effects.
Having side effects prevent bundlers from applying some tree shaking techniques to reduce the size of the `maxGraph` part bundled in application. So, some unused parts of `maxGraph` may remain in the application.

Here are some information about how various bundlers performs tree shaking regarding the "side effects" aspects
- webpack https://webpack.js.org/guides/tree-shaking/ and https://webpack.js.org/configuration/optimization/#optimizationsideeffects
- rollup https://rollupjs.org/configuration-options/#treeshake
- parcel https://parceljs.org/features/scope-hoisting/#side-effects
- esbuild: https://esbuild.github.io/api/#tree-shaking-and-side-effects

### Describe the solution you'd like

As a long term objective, the `maxGraph` package should not contain side effects. As an intermediate step, it could declare explicitly which modules include side effects and progressively remove them.

### Additional context

Some actions have already been taken to remove some side effects.
- Codecs https://github.com/maxGraph/maxGraph/pull/289 in https://github.com/maxGraph/maxGraph/releases/tag/v0.6.0 This change already had a positive impact on the tree shaking as Codecs are no longer loaded by default.
- Default style resources registration. This will also help changing the default and/or not loading part or all defaults in the future
  - Shapes, Perimeters, Edge Styles: https://github.com/maxGraph/maxGraph/pull/311 in https://github.com/maxGraph/maxGraph/releases/tag/v0.8.0
  - Edge Markers: https://github.com/maxGraph/maxGraph/pull/436 in upcoming version 0.11.0

All these actions have been inspired by discussions in https://github.com/maxGraph/maxGraph/issues/1#issuecomment-744329390 (December 2020) and what was done in https://github.com/adrianhdezm/mxgraph-es6/blob/cafafa9212e51062d5ac96c0e1d03ce334bb28f5/src/bootstrap.js#L157-L222

AFAIK, the latest remaining side effects are in the Graph mixins.
They are imported in index.ts, and each imported file registers a mixin
  - imports in index.ts: https://github.com/maxGraph/maxGraph/blob/v0.10.3/packages/core/src/index.ts#L17-L40
  - example of side effects: https://github.com/maxGraph/maxGraph/blob/v0.10.3/packages/core/src/view/mixins/ImageMixin.ts#L80

### Remaining Tasks

```[tasklist]
### Tasks
- [x] Update Mixin types to hold the JSDoc which is currently located on the value mixins
- [x] Remove all side effects produced by the Graph mixins #470
- [x] Set `sideEffects: false` in `package.json` #484
```
